server:
  port: 8801
spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  sentinel:
    transport:
      port: 8903
      dashboard: 127.0.0.1:8080